//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARTIS_manager.ARTISref {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://itec-web-dev04.radford.edu/ews", ConfigurationName="ARTISref.ArtisLabInfoServiceSoap")]
    public interface ArtisLabInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/logIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logIn(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/sysLogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sysLogOut(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/sysLogOut", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sysLogOutAsync(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/addSysAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addSysAdmin(string username, string firstname, string lastname, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/addSysAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addSysAdminAsync(string username, string firstname, string lastname, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/deleteSysAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteSysAdmin(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/deleteSysAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteSysAdminAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARTIS_manager.ARTISref.User getUser(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ARTIS_manager.ARTISref.User> getUserAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResource", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARTIS_manager.ARTISref.Resource getResource(string rname, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResource", ReplyAction="*")]
        System.Threading.Tasks.Task<ARTIS_manager.ARTISref.Resource> getResourceAsync(string rname, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/addNewUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARTIS_manager.ARTISref.User addNewUser(string username, string usertype, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/addNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ARTIS_manager.ARTISref.User> addNewUserAsync(string username, string usertype, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getInactiveUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getInactiveUsers(int daysInactive, string usertype, string status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getInactiveUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getInactiveUsersAsync(int daysInactive, string usertype, string status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/sunsetRetiredUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sunsetRetiredUsers(string usertype, int graceDays, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/sunsetRetiredUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sunsetRetiredUsersAsync(string usertype, int graceDays, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/searchUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable searchUsers(string usertype, string status, string stringToFind, int DaysInactiveCutoff, int UsesIn90DaysCutOff, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/searchUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> searchUsersAsync(string usertype, string status, string stringToFind, int DaysInactiveCutoff, int UsesIn90DaysCutOff, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResourceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getResourceList();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResourceList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getResourceListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResourceUsage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getResourceUsage(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getResourceUsage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getResourceUsageAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUserList(string usertype, string status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserListAsync(string usertype, string status, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getSysAdminList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSysAdminList(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getSysAdminList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSysAdminListAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getPrivList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPrivList();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getPrivList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPrivListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserTypeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUserTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserTypeList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserTypeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserStatusList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUserStatusList();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/getUserStatusList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getUserStatusListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/saveUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveUser(ARTIS_manager.ARTISref.User userToSave, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/saveUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saveUserAsync(ARTIS_manager.ARTISref.User userToSave, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/deleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteUser(string UsernameToDelete, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://itec-web-dev04.radford.edu/ews/deleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteUserAsync(string UsernameToDelete, string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://itec-web-dev04.radford.edu/ews")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string statusField;
        
        private string usertypeField;
        
        private System.DateTime createdateField;
        
        private System.DateTime estsunsetdateField;
        
        private System.DateTime sunsetdateField;
        
        private string notesField;
        
        private string errmessageField;
        
        private System.Data.DataTable privUseSetField;
        
        private System.Data.DataTable pastReservationsField;
        
        private System.Data.DataTable futureReservationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string usertype {
            get {
                return this.usertypeField;
            }
            set {
                this.usertypeField = value;
                this.RaisePropertyChanged("usertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime createdate {
            get {
                return this.createdateField;
            }
            set {
                this.createdateField = value;
                this.RaisePropertyChanged("createdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime estsunsetdate {
            get {
                return this.estsunsetdateField;
            }
            set {
                this.estsunsetdateField = value;
                this.RaisePropertyChanged("estsunsetdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime sunsetdate {
            get {
                return this.sunsetdateField;
            }
            set {
                this.sunsetdateField = value;
                this.RaisePropertyChanged("sunsetdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string errmessage {
            get {
                return this.errmessageField;
            }
            set {
                this.errmessageField = value;
                this.RaisePropertyChanged("errmessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.Data.DataTable PrivUseSet {
            get {
                return this.privUseSetField;
            }
            set {
                this.privUseSetField = value;
                this.RaisePropertyChanged("PrivUseSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Data.DataTable PastReservations {
            get {
                return this.pastReservationsField;
            }
            set {
                this.pastReservationsField = value;
                this.RaisePropertyChanged("PastReservations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Data.DataTable FutureReservations {
            get {
                return this.futureReservationsField;
            }
            set {
                this.futureReservationsField = value;
                this.RaisePropertyChanged("FutureReservations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://itec-web-dev04.radford.edu/ews")]
    public partial class Resource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rnameField;
        
        private string descriptionField;
        
        private string statusField;
        
        private string notesField;
        
        private string errmessageField;
        
        private int usesInLast90DaysField;
        
        private int usesInLastYearField;
        
        private int allUsesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rname {
            get {
                return this.rnameField;
            }
            set {
                this.rnameField = value;
                this.RaisePropertyChanged("rname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string errmessage {
            get {
                return this.errmessageField;
            }
            set {
                this.errmessageField = value;
                this.RaisePropertyChanged("errmessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UsesInLast90Days {
            get {
                return this.usesInLast90DaysField;
            }
            set {
                this.usesInLast90DaysField = value;
                this.RaisePropertyChanged("UsesInLast90Days");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int UsesInLastYear {
            get {
                return this.usesInLastYearField;
            }
            set {
                this.usesInLastYearField = value;
                this.RaisePropertyChanged("UsesInLastYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int AllUses {
            get {
                return this.allUsesField;
            }
            set {
                this.allUsesField = value;
                this.RaisePropertyChanged("AllUses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtisLabInfoServiceSoapChannel : ARTIS_manager.ARTISref.ArtisLabInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtisLabInfoServiceSoapClient : System.ServiceModel.ClientBase<ARTIS_manager.ARTISref.ArtisLabInfoServiceSoap>, ARTIS_manager.ARTISref.ArtisLabInfoServiceSoap {
        
        public ArtisLabInfoServiceSoapClient() {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtisLabInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtisLabInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string logIn(string strUsername, string strPassword) {
            return base.Channel.logIn(strUsername, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword) {
            return base.Channel.logInAsync(strUsername, strPassword);
        }
        
        public string sysLogOut(string strToken) {
            return base.Channel.sysLogOut(strToken);
        }
        
        public System.Threading.Tasks.Task<string> sysLogOutAsync(string strToken) {
            return base.Channel.sysLogOutAsync(strToken);
        }
        
        public string addSysAdmin(string username, string firstname, string lastname, string token) {
            return base.Channel.addSysAdmin(username, firstname, lastname, token);
        }
        
        public System.Threading.Tasks.Task<string> addSysAdminAsync(string username, string firstname, string lastname, string token) {
            return base.Channel.addSysAdminAsync(username, firstname, lastname, token);
        }
        
        public string deleteSysAdmin(string username, string token) {
            return base.Channel.deleteSysAdmin(username, token);
        }
        
        public System.Threading.Tasks.Task<string> deleteSysAdminAsync(string username, string token) {
            return base.Channel.deleteSysAdminAsync(username, token);
        }
        
        public ARTIS_manager.ARTISref.User getUser(string username, string token) {
            return base.Channel.getUser(username, token);
        }
        
        public System.Threading.Tasks.Task<ARTIS_manager.ARTISref.User> getUserAsync(string username, string token) {
            return base.Channel.getUserAsync(username, token);
        }
        
        public ARTIS_manager.ARTISref.Resource getResource(string rname, string token) {
            return base.Channel.getResource(rname, token);
        }
        
        public System.Threading.Tasks.Task<ARTIS_manager.ARTISref.Resource> getResourceAsync(string rname, string token) {
            return base.Channel.getResourceAsync(rname, token);
        }
        
        public ARTIS_manager.ARTISref.User addNewUser(string username, string usertype, string token) {
            return base.Channel.addNewUser(username, usertype, token);
        }
        
        public System.Threading.Tasks.Task<ARTIS_manager.ARTISref.User> addNewUserAsync(string username, string usertype, string token) {
            return base.Channel.addNewUserAsync(username, usertype, token);
        }
        
        public System.Data.DataTable getInactiveUsers(int daysInactive, string usertype, string status, string token) {
            return base.Channel.getInactiveUsers(daysInactive, usertype, status, token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getInactiveUsersAsync(int daysInactive, string usertype, string status, string token) {
            return base.Channel.getInactiveUsersAsync(daysInactive, usertype, status, token);
        }
        
        public string sunsetRetiredUsers(string usertype, int graceDays, string token) {
            return base.Channel.sunsetRetiredUsers(usertype, graceDays, token);
        }
        
        public System.Threading.Tasks.Task<string> sunsetRetiredUsersAsync(string usertype, int graceDays, string token) {
            return base.Channel.sunsetRetiredUsersAsync(usertype, graceDays, token);
        }
        
        public System.Data.DataTable searchUsers(string usertype, string status, string stringToFind, int DaysInactiveCutoff, int UsesIn90DaysCutOff, string token) {
            return base.Channel.searchUsers(usertype, status, stringToFind, DaysInactiveCutoff, UsesIn90DaysCutOff, token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> searchUsersAsync(string usertype, string status, string stringToFind, int DaysInactiveCutoff, int UsesIn90DaysCutOff, string token) {
            return base.Channel.searchUsersAsync(usertype, status, stringToFind, DaysInactiveCutoff, UsesIn90DaysCutOff, token);
        }
        
        public System.Data.DataTable getResourceList() {
            return base.Channel.getResourceList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getResourceListAsync() {
            return base.Channel.getResourceListAsync();
        }
        
        public System.Data.DataTable getResourceUsage(string token) {
            return base.Channel.getResourceUsage(token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getResourceUsageAsync(string token) {
            return base.Channel.getResourceUsageAsync(token);
        }
        
        public System.Data.DataTable getUserList(string usertype, string status, string token) {
            return base.Channel.getUserList(usertype, status, token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserListAsync(string usertype, string status, string token) {
            return base.Channel.getUserListAsync(usertype, status, token);
        }
        
        public System.Data.DataTable getSysAdminList(string token) {
            return base.Channel.getSysAdminList(token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSysAdminListAsync(string token) {
            return base.Channel.getSysAdminListAsync(token);
        }
        
        public System.Data.DataTable getPrivList() {
            return base.Channel.getPrivList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPrivListAsync() {
            return base.Channel.getPrivListAsync();
        }
        
        public System.Data.DataTable getUserTypeList() {
            return base.Channel.getUserTypeList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserTypeListAsync() {
            return base.Channel.getUserTypeListAsync();
        }
        
        public System.Data.DataTable getUserStatusList() {
            return base.Channel.getUserStatusList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getUserStatusListAsync() {
            return base.Channel.getUserStatusListAsync();
        }
        
        public string saveUser(ARTIS_manager.ARTISref.User userToSave, string token) {
            return base.Channel.saveUser(userToSave, token);
        }
        
        public System.Threading.Tasks.Task<string> saveUserAsync(ARTIS_manager.ARTISref.User userToSave, string token) {
            return base.Channel.saveUserAsync(userToSave, token);
        }
        
        public string deleteUser(string UsernameToDelete, string Token) {
            return base.Channel.deleteUser(UsernameToDelete, Token);
        }
        
        public System.Threading.Tasks.Task<string> deleteUserAsync(string UsernameToDelete, string Token) {
            return base.Channel.deleteUserAsync(UsernameToDelete, Token);
        }
    }
}
